package com.example.ivss.server.services

object FormatoVacaciones {
    const val PARA = "DIRECCIÓN GENERAL DE RECURSOS HUMANOS Y ADMINISTRACIÓN DE PERSONAL"
    const val DE = "HOSPITAL GENERAL MUNICIPAL IVSS SAN JUAN DE LOS MORROS."

    const val TITULO_APELLIDOS = "APELLIDOS Y NOMBRES"
    const val TITULO_CEDULA = "CÉDULA DE IDENTIDAD N°"
    const val TITULO_DENOMINACION = "DENOMINACIÓN DEL CARGO"
    const val TITULO_NUMERO_CARGO = "N° DE CARGO"
    const val TITULO_FECHA_INGRESO = "FECHA DE INGRESO"
    const val TITULO_COD_ORIGEN = "COD. ORIGEN Y SERV."
    const val TITULO_UNIDAD = "UNIDAD O SERVICIO"
    const val TITULO_LUGAR = "LUGAR"
    const val TITULO_HORARIO = "HORARIO"

    const val TEXTO_TOMA_VACACIONES = "EL TRABAJADOR O TRABAJADORA, TOMARÁ SUS VACACIONES EN EL LAPSO SEÑALADO"
    const val TITULO_LAPSO = "LAPSO DE DISFRUTE DE VACACIONES"
    const val TITULO_DESDE = "DESDE"
    const val TITULO_HASTA = "HASTA"
    const val TITULO_PERIODO = "PERIODO"
    const val TITULO_DIAS = "N° DE DÍAS"

    const val TEXTO_REINTEGRO = "HÁBILES, DEBERÁ REINTEGRARSE EL DÍA:"

    const val TITULO_OBSERVACIONES = "OBSERVACIONES:"
    const val TITULO_NOTA = "NOTA:"

    const val FIRMA_SUPERVISOR = "SUPERVISOR INMEDIATO:"
    const val FIRMA_COORDINADOR = "COORDINADOR DE RECURSOS HUMANOS:"
    const val FIRMA_MAXIMA = "MÁXIMA AUTORIDAD - DIRECTOR/DIRECTORA:"
    const val FIRMA_TRABAJADOR = "TRABAJADOR O TRABAJADORA:"

    const val LABEL_NOMBRE_APELLIDO = "NOMBRE Y APELLIDO"
    const val LABEL_FIRMA_SELLO = "FIRMA Y SELLO"
    const val LABEL_FIRMA = "FIRMA"
}
